### ISSUE TITLE
how to convert yolov4-tiny-3l model ?

### ISSUE THREAD

**Issue by zhongwenkun886** [TNTWEN/OpenVINO-YOLOV4#20]
hi , I have trained the yolov4-tiny-3l model , but how to convert it to openVINO?
thanks.

**Comment by TNTWEN** [comment]
Hi!
Since tensorflow1.x based on static graph design is used, if the model is adjusted, tensorlow code needs to be rewritten.
You need to modify these parts according to the model you are using:
https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/f7d066c56c5878dac2a9cc8603cb773e7c1dcd42/yolo_v4_tiny.py#L79-L109
https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/f7d066c56c5878dac2a9cc8603cb773e7c1dcd42/yolo_v4_tiny.json#L10-L11


This means that you need to try to understand and adjust the tensorflow part of the code.For me, if we want to deploy YOLO on the embedded edge, I prefer to optimize the full version of the model. For the full yolov3/v4（not tiny）model, I made a script that automatically generates tensorflow code  https://github.com/TNTWEN/OpenVINO-YOLO-Automatic-Generation.
After November 9th, I will share how to optimize the full version of the model to get several times faster on OpenVINO without losing accuracy.

**Comment by zhongwenkun886** [comment]
thinks

**Comment by TNTWEN** [comment]
@zhongwenkun886 
https://github.com/TNTWEN/OpenVINO-YOLOV4/tree/v4-tiny-3l
