### ISSUE TITLE
The running of yolov4.bin+openvino+ncs2 is very slow

### ISSUE THREAD

**Issue by dsp6414** [TNTWEN/OpenVINO-YOLOV4#4]
i get FPS =1.5, what is The reason ,The running speed is  so slowly.

**Comment by TNTWEN** [comment]
Hi,@dsp6414
I think the FPS you get is normal. The network of V4/3 is very large. Even on the GPU of Intel i5-8250u, there is only 2~3fps.The computing power of ncs2 is not strong.
If you have done a video test of V3 / 4tiny, you will find that the effect of target detection is very unstable.
Here are the Video tests i have done:
Video Test: (OpenVINO v4tiny,v3tiny)

YOLOv4-tiny
(yolov4-tiny.weights->https://github.com/TNTWEN/OpenVINO-YOLOV4->OpenVINO)
Video url :https://drive.google.com/file/d/1AXQ5Z_E-G04CdKKPwnrQQw4DEDJIMlBd/view?usp=sharing

YOLOv3-tiny
(yolov3-tiny.weights->https://github.com/mystic123/tensorflow-yolo-v3->OpenVINO)
Video url:https://drive.google.com/file/d/1mIW7ITf7kkOShEftK5VNbJw8u2HW4jMq/view?usp=sharing

Therefore you can find that v3 / v4 and v3 / v4tiny are difficult to meet the requirements of real-time and stability in practical use.This problem has existed since v3 .It is normal, because the performance of NVIDIA GPU is far better than the devices supported by openvino, although Intel has done a lot of optimization in NCS2, CPU , integrated GPU and so on.

So we need to compromise between the v3/v4 and v3/v4 tiny.This is what I'm doing at this stage. I will open a new repository in the future to share OpenVINO YOLOV4/3 model optimization to make it faster and stable.And in this project, I pay more attention to the accuracy of the model compared with darknet and other frameworks.

Thanks for your trying！

**Comment by TNTWEN** [comment]
You could star and collect this project and give attention to the future updates!

**Comment by dsp6414** [comment]
Thank you for your patience. I will follow this project closely.

**Comment by lijunnankman** [comment]
@dsp6414 have you check the "util%" when you run you project? I think your "util%" is not the highest.
