### ISSUE TITLE
-reverse input channel flag needed

### ISSUE THREAD

**Issue by GotG** [TNTWEN/OpenVINO-YOLOV4#8]
Hello

When converting to xml wondering whether reverse input channel is needed?

In my experience, tf models do require this.

Thanks

**Comment by TNTWEN** [comment]
Hi, @GotG 
Darknet:https://github.com/pjreddie/darknet/issues/427
Tensorflow(my project is based on mystics123 Tensorflow YOLOV3):https://github.com/mystic123/tensorflow-yolo-v3/issues/2
OpenVINOYOLOV3:https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html
`python3 mo_tf.py
--input_model /path/to/yolo_v3.pb
--tensorflow_use_custom_operations_config $MO_ROOT/extensions/front/tf/yolo_v3.json
--batch
Since YOLOV3 ,OpenVINO didn't use --reverse_input_channels. I checked object_detection_demo_yolov3_async.py and i didn't found this demo converts BGR(OpenCV) to RGB(darknet and tf)
So i did some tests:
YOLOV4 original:
![oldyolov4](https://user-images.githubusercontent.com/49018311/90537229-aa3ef300-e1af-11ea-8a78-cb0f7a12bce4.png)
YOLOV4 channels reversed:
![yolov4](https://user-images.githubusercontent.com/49018311/90537285-bb87ff80-e1af-11ea-85bd-98a4f74340fb.png)
YOLOV4 tiny original:
![oldv4tiny416](https://user-images.githubusercontent.com/49018311/90537320-c773c180-e1af-11ea-926e-11d15d0319e9.png)
YOLOV4 tiny  channels reversed:
![V4tiny](https://user-images.githubusercontent.com/49018311/90537380-d8bcce00-e1af-11ea-9321-42f49aaef5b4.png)


I also do some video tests,the results are the same. Using --reverse_input_channels will be better
So i agree with you. My conclusion is that this may be a mistake made by OpenVINO since YOLOv3

Thanks a lot!!

**Comment by GotG** [comment]
Thanks for checking. My results are also very close when tested on yolov3. I did mention this at some point on their forums.

**Comment by TNTWEN** [comment]
Great job!!
Thanks a lot!

**Comment by GotG** [comment]
Well done with your repo! Very useful!
Do you happen to know for tiny yolo v4 which function prevents it from working in OpenVINO 20.01 or .02? Thanks

**Comment by TNTWEN** [comment]
yolov4 tiny need this :

[route]
layers=-1
groups=2
group_id=1

In Tensorflow,we could use https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/534cca38d1e3bf95dce98daa216a57f62a2f83ce/yolo_v4_tiny.py#L21
or https://github.com/TNTWEN/OpenVINO-YOLOV4/blob/534cca38d1e3bf95dce98daa216a57f62a2f83ce/yolo_v4_tiny.py#L22
But they are not supported by OpenVINO before 2020R4(In fact, I  used the 2019 version before ,so the exact version which began to support v4 tiny may not  be accurate)
Now OpenVINO 2020R4 supports the second operation but it still doesn't support the first operation.But anyway, that's enough for us to implement  OpenVINO v4tiny
